name: myenv
channels:
  - defaults
dependencies:
  - python=3.9  
  - pip
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - joblib
  - streamlit
  - imbalanced-learn  
  - openpyxl
  - tabulate
  - xgboost
  - lightGBM